DATA SEGMENT
A db 12h, 00h, 12h, 56h, 34, 11h
len db $-A
NL db 10, 13, '$'
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START:
 MOV AX, data
 MOV DS, AX
 MOV CL, 00H
 MOV DL, len
 SUB DL, 01H ; DL HOLDS len-1
LOOP1: CMP CL, DL
 JZ DISPL
 MOV BX, 0000H
 MOV DH, DL
 SUB DH, CL ; DH holds len-1-i
LOOP2: CMP BL, DH
 JB L2
 INC CL
 JMP LOOP1
L2: MOV AL, A[BX]
 MOV AH, A[BX+1]
 CMP AL, AH
 JBE L1
 MOV A[BX], AH
 MOV A[BX+1], AL
L1: INC BL
 JMP LOOP2
DISPL: MOV BX, 0000h
REPEAT: MOV DL, A[BX] ; display the 1st digit
 AND DL, 0F0h
 MOV CL, 04h
 SHR DL, CL
 CMP DL, 09H
 JBE L3
 ADD DL, 07H
L3: ADD DL, 30H
 MOV AH, 02H
 INT 21H
 MOV DL, A[BX] ; display the 2nd digit
 AND DL, 0FH
 CMP DL, 09H
 JBE L4
 ADD DL, 07H
L4: ADD DL, 30H
 MOV AH, 02H
 INT 21H
 LEA DX, NL ; TO DISPLAY NEW LINE
 MOV AH, 09H
 INT 21H
 INC BX
 CMP BL, LEN
 JZ EXIT 
 JMP REPEAT
EXIT: MOV AH, 4CH
 INT 21H
CODE ENDS
END START