DATA SEGMENT
 FNAME DB 'ABCD.DAT', 0
 MSG1 DB 'DELETE Y/N$'
DATA ENDS
CODE SEGMENT
ASSUME CS: CODE, DS: DATA
START:
 MOV AX, DATA
 MOV DS, AX
 LEA DX, FNAME ; TO CREATE FILE NAMED 'ABC.DAT'
 MOV CX, 20H
 MOV AH, 3CH
 INT 21H
 LEA DX, MSG1
 MOV AH, 09H ; TO DISPLAY MSG1 
 INT 21H
 MOV AH, 01H ; TO READ CHAR EITHER 'Y' OR 'N'
 INT 21H
 CMP AL, 'Y'
 JNE EXIT ; IF 'N' THEN DONT DELETE FILE
 LEA DX, FNAME ; IF 'Y' THEN DELETE FILE
 MOV AH, 41H
 INT 21H ; TO DELETE FILE 'ABC.DAT'
 JC ERROR
; WRITE CODE HERE TO DISPLAY MSG “FILE DELETED”
 JMP EXIT
ERROR:
; WRITE CODE HERE TO DISPLAY MSG “FILE CANNOT BE DELETED”
EXIT: MOV AH, 4CH
 INT 21H
CODE ENDS
END START