INCLUDE F1.MAC ;INCLUDE FILE WHERE U HAVE WRITTEN READ MACRO
INCLUDE F2.MAC ;INCLUDE FILE WHERE U HAVE WRITTEN WRITE MACRO
DATA SEGMENT
MSG DB 10,13,'ENTER A STRING',10,13,'$'
MSG2 DB 10,13,'ENTERED STRING IS:',10,13,'$'
STR DB 50 DUP(?)
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE,DS:DATA
START: MOV AX,DATA
 MOV DS,AX
MOV CL,0
 LEA SI,STR 
 MOV DX,OFFSET MSG
 MOV AH,09H
 INT 21H
 UP: READ 
 MOV [SI],AL 
 INC SI
CMP AL,0DH 
 JE DOWN
 INC CL
 CMP CL,50
 JNE UP 
DOWN: LEA SI,STR 
 MOV DX,OFFSET MSG2
 MOV AH,09H
 INT 21H
 UP1: MOV AL,[SI] 
 WRITE
 DEC CL 
 INC SI
 CMP CL,0
 JNZ UP1
 MOV AH,4CH
 INT 21H
 CODE ENDS
 END START